# Generated by Django 5.1.3 on 2024-12-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_status',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
